"""Added required tables

Revision ID: 5875f157aef3
Revises: e7292fe924fb
Create Date: 2022-10-17 16:35:19.890131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5875f157aef3'
down_revision = 'e7292fe924fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
